config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get 'worker-processses-status', to: 'sidekiq_monitor#processes_status'

  localized do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }

    namespace :api do
      namespace :v2 do
        resources :exam_rules, only: [:index]
        get 'step_activity', to: 'step_activity#check'
        get 'discipline_activity', to: 'discipline_activity#check'
        get 'student_activity', to: 'student_activity#check'
        resources :teacher_unities, only: [:index]
        resources :teacher_classrooms, only: [:index] do
          collection do
            get :has_activities
          end
        end
        resources :teacher_disciplines, only: [:index]
        resources :school_calendars, only: [:index]
        resources :daily_frequencies, only: [:create, :index]
        resources :daily_frequency_students, only: [:update] do
          collection do
            post :update_or_create
          end
        end
        resources :classroom_students, only: [:index]
        resources :teacher_allocations, only: [:index]
        resources :lesson_plans, only: [:index]
        resources :content_records, only: [:index] do
          collection do
            get :lesson_plans
            post :sync
          end
        end
        resources :teaching_plans, only: [:index]
      end
    end

    concern :history do
      member do
        get :history
      end
    end

    resources :registrations do
      collection do
        get :parents
        get :students
        post :students
        get :employees
        post :employees
      end
    end

    resources :students do
      collection do
        get :search_api
        get :in_recovery
        get :select2_remote
        get :in_final_recovery, path: '/in_final_recovery/classrooms/:classroom_id/disciplines/:discipline_id'
      end
    end

    resources :teachers, only: :index do
      collection do
        get :select2
      end
    end

    resources :teacher_profiles, only: :index

    resources :system_notifications, only: :index

    root 'dashboard#index'

    namespace :dashboard do
      resources :student_partial_scores, only: [:index]
      resources :teacher_next_avaliations, only: [:index]
      resources :teacher_pending_avaliations, only: [:index]
      resources :teacher_work_done_chart, only: [:index]
    end

    post '/current_role', to: 'current_role#set', as: :set_current_role
    get '/current_role/available_classrooms', to: 'current_role#available_classrooms', as: :available_classrooms
    get '/current_role/available_disciplines', to: 'current_role#available_disciplines', as: :available_disciplines
    get '/current_role/available_school_years', to: 'current_role#available_school_years', as: :available_school_years
    get '/current_role/available_teachers', to: 'current_role#available_teachers', as: :available_teachers
    get '/current_role/available_unities', to: 'current_role#available_unities', as: :available_unities
    get '/current_role/available_teacher_profiles', to: 'current_role#available_teacher_profiles', as: :available_teacher_profiles
    get '/steps_by_school_term_type_id', to: 'school_term_type_steps#steps', as: :steps_by_school_term_type_id
    post '/system_notifications/read_all', to: 'system_notifications#read_all', as: :read_all_notifications
    get '/disabled_entity', to: 'pages#disabled_entity'

    resources :users, concerns: :history do
      collection do
        get :export_all
        get :export_selected
        get :select2_remote
        post :profile_picture
      end
    end

    resource :account, only: [:edit, :update]
    resources :roles do
      member do
        get :history
      end
    end
    resources  :user_roles, only: [:show]
    resource :ieducar_api_configurations, only: [:edit, :update], concerns: :history do
      resources :synchronizations, only: [:index, :create] do
        collection do
          get :current_syncronization_data
        end
      end
    end
    resource :general_configurations, only: [:edit, :update], concerns: :history
    resource :entity_configurations, only: [:edit, :update], concerns: :history
    resource :terms_dictionaries, only: [:edit, :update], concerns: :history
    resources :admin_synchronizations, only: [:index]
    resources :backup_files, only: [:index, :create]
    resources :unities, concerns: :history do
      collection do
        delete :destroy_batch
        get :search
        get :all
        get :select2_remote
      end
    end
    resources :courses, only: [:index]
    resources :lectures, only: [:index]
    resources :maintenance_adjustments, concerns: :history, except: :show do
      collection do
        get :any_completed
      end
    end

    resources :grades, only: [:index]

    resources :schools, only: [:index]

    resources :custom_rounding_tables, concerns: :history, except: :show
    resources :custom_rounding_tables, concerns: :history, except: :show

    resources :test_settings, concerns: :history do
      resources :test_setting_tests, only: [:index]
      get :grades_by_unities, on: :collection
    end
    resources :test_setting_tests, only: [:index, :show]

    resources :school_calendar_event_batches
    resources :school_calendars, concerns: :history do
      collection do
        get :step
        get :years_from_unity
      end

      resources :school_calendar_steps, only: [:index]
      resources :school_calendar_events, concerns: :history do
        collection do
          get  :grades
          get  :classrooms
        end
      end
    end
    resources :school_calendar_steps, only: [:show, :index]
    resources :school_calendar_classroom_steps, only: [:show, :index]

    resources :discipline_teaching_plans, concerns: :history
    resources :knowledge_area_teaching_plans, concerns: :history
    resources :learning_objectives_and_skills, concerns: :history do
      collection do
        get :contents
      end
    end

    get '/pedagogical_trackings', as: :pedagogical_trackings, to: 'pedagogical_trackings#index'
    get '/pedagogical_trackings_teachers', as: :pedagogical_trackings_teachers, to: 'pedagogical_trackings#teachers'
    get '/translations', as: :translations, to: 'translations#form'
    post '/translations', as: :save_translations, to: 'translations#save'
    resources :discipline_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
      end
    end
    resources :knowledge_area_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
      end
    end
    resources :discipline_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :knowledge_area_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :classrooms, only: [:index, :show] do
      resources :students, only: [:index]
    end
    resources :contents, only: :index
    resources :disciplines, only: [:index] do
      collection do
        get :search
        get :search_grouped_by_knowledge_area
      end
    end
    resources :knowledge_areas, only: [:index]
    resources :exam_rules, only: [:index]
    resources :avaliations, concerns: :history do
      collection do
        get :search
        get :multiple_classrooms
        post :create_multiple_classrooms
      end
    end
    resources :complementary_exam_settings, concerns: :history
    resources :complementary_exams, concerns: :history do
      collection do
        get :settings
      end
    end
    resources :teacher_avaliations, only: :index
    resources :daily_notes, only: [:index, :new, :create, :edit, :update, :destroy], concerns: :history do
      collection do
        get :search
      end
    end
    resources :daily_note_students, only: [:index] do
      collection do
        get :old_notes
        get :dependence
      end
    end
    resources :school_term_recovery_diary_records, concerns: :history
    resources :transfer_notes, concerns: :history do
      collection do
        get :current_notes
      end
    end
    resources :final_recovery_diary_records, concerns: :history
    resources :avaliation_recovery_diary_records, concerns: :history
    resources :conceptual_exams, concerns: :history do
      collection do
        get :exempted_disciplines
        get :find_conceptual_exam_by_student
      end
    end
    resources :old_steps_conceptual_values, except: [:only]
    resources :descriptive_exams, only: [:new, :create, :edit, :update], concerns: :history do
      collection do
        get :opinion_types
      end
    end
    resources :daily_frequencies, only: [:new, :create], concerns: :history do
      collection do
        get :edit_multiple
        put :create_or_update_multiple
        delete :destroy_multiple
      end
    end
    get 'daily_frequency/history_multiple', to: 'daily_frequencies#history_multiple', as: 'history_multiple_daily_frequency'

    resources :absence_justifications, concerns: :history
    resources :observation_diary_records, except: :show, concerns: :history
    resources :ieducar_api_exam_postings do
      member do
        get :done_percentage
      end
    end
    resources :avaliation_exemptions, concerns: :history

    resources :daily_frequency_students do
      collection do
        post :create_or_update
      end
    end

    resources :infrequency_trackings, only: :index

    resources :student_enrollments, only: [:index]
    resources :student_enrollments_lists, only: [:index] do
      collection do
        get :by_date
        get :by_date_range
      end
    end

app/controllers/knowledge_area_content_records_controller.rb
class KnowledgeAreaContentRecordsController < ApplicationController
  has_scope :page, default: 1
  has_scope :per, default: 10

  before_action :require_current_teacher
  before_action :require_allow_to_modify_prev_years, only: [:create, :update, :destroy, :clone]

  def index
    params[:filter] ||= {}
    author_type = PlansAuthors::MY_PLANS if params[:filter].empty?
    author_type ||= (params[:filter] || []).delete(:by_author)

    @knowledge_area_content_records = apply_scopes(
      KnowledgeAreaContentRecord.includes(:knowledge_areas, content_record: [:classroom])
                                .by_classroom_id(current_user_classroom)
                                .ordered
    )

    if author_type.present?
      @knowledge_area_content_records = @knowledge_area_content_records.by_author(author_type, current_teacher)
      params[:filter][:by_author] = author_type
    end

    authorize @knowledge_area_content_records
  end

  def new
    @knowledge_area_content_record = KnowledgeAreaContentRecord.new.localized
    @knowledge_area_content_record.build_content_record(
      record_date: Time.zone.now,
      unity_id: current_unity.id
    )

    authorize @knowledge_area_content_record
  end

  def create
    @knowledge_area_content_record = KnowledgeAreaContentRecord.new(resource_params)
    @knowledge_area_content_record.knowledge_area_ids = resource_params[:knowledge_area_ids].split(',')
    @knowledge_area_content_record.content_record.teacher = current_teacher
    @knowledge_area_content_record.content_record.content_ids = content_ids
    @knowledge_area_content_record.content_record.origin = OriginTypes::WEB
    @knowledge_area_content_record.content_record.teacher = current_teacher
    @knowledge_area_content_record.teacher_id = current_teacher_id

    authorize @knowledge_area_content_record

    if @knowledge_area_content_record.save
      respond_with @knowledge_area_content_record, location: knowledge_area_content_records_path
    else
      render :new
    end
  end

  def edit
    @knowledge_area_content_record = KnowledgeAreaContentRecord.find(params[:id]).localized

    authorize @knowledge_area_content_record
  end

  def update
    @knowledge_area_content_record = KnowledgeAreaContentRecord.find(params[:id])
    @knowledge_area_content_record.assign_attributes(resource_params)
    @knowledge_area_content_record.knowledge_area_ids = resource_params[:knowledge_area_ids].split(',')
    @knowledge_area_content_record.content_record.content_ids = content_ids
    @knowledge_area_content_record.teacher_id = current_teacher_id
    @knowledge_area_content_record.content_record.current_user = current_user

    authorize @knowledge_area_content_record

    if @knowledge_area_content_record.save
      respond_with @knowledge_area_content_record, location: knowledge_area_content_records_path
    else
      render :edit
    end
  end

  def destroy
    @knowledge_area_content_record = KnowledgeAreaContentRecord.find(params[:id]).localized

    authorize @knowledge_area_content_record

    @knowledge_area_content_record.destroy

    respond_with @knowledge_area_content_record, location: knowledge_area_content_records_path
  end

  def history
    @knowledge_area_content_record = KnowledgeAreaContentRecord.find(params[:id])

    authorize @knowledge_area_content_record

    respond_with @knowledge_area_content_record
  end

  def clone
    @form = KnowledgeAreaContentRecordClonerForm.new(clone_params.merge(teacher: current_teacher))

    flash[:success] = t('messages.copy_succeed') if @form.clone!
  end

  private

  def content_ids
    param_content_ids = params[:knowledge_area_content_record][:content_record_attributes][:content_ids] || []
    content_descriptions = params[:knowledge_area_content_record][:content_record_attributes][:content_descriptions] || []
    new_contents_ids = content_descriptions.map { |content_description|
      Content.find_or_create_by!(description: content_description).id
    }
    param_content_ids + new_contents_ids
  end

  def resource_params
    params.require(:knowledge_area_content_record).permit(
      :knowledge_area_ids,
      content_record_attributes: [
        :id,
        :unity_id,
        :classroom_id,
        :record_date,
        :daily_activities_record,
        :content_ids
      ]
    )
  end

  def clone_params
    params.require(:knowledge_area_content_record_cloner_form).permit(
      :knowledge_area_content_record_id,
      knowledge_area_content_record_item_cloner_form_attributes: [
        :uuid,
        :classroom_id,
        :record_date
      ]
    )
  end

  def contents
    @contents = []
    teacher = current_teacher
    classroom = @knowledge_area_content_record.content_record.classroom
    knowledge_areas = @knowledge_area_content_record.knowledge_areas
    date = @knowledge_area_content_record.content_record.record_date

    if teacher && classroom && knowledge_areas && date
      @contents = ContentsForKnowledgeAreaRecordFetcher.new(teacher, classroom, knowledge_areas, date).fetch
      @contents.each { |content| content.is_editable = false }
    end

    if @knowledge_area_content_record.content_record.contents
      contents = @knowledge_area_content_record.content_record.contents_ordered
      contents.each { |content| content.is_editable = true }
      @contents << contents
    end

    @contents.flatten.uniq
  end
  helper_method :contents

  def all_contents
    Content.ordered
  end
  helper_method :all_contents

  def fetch_collections
    fetch_unities
    fetch_grades
    fetch_knowledge_areas
  end

  def unities
    @unities = [current_unity]
  end
  helper_method :unities

  def classrooms
    @classrooms = Classroom.by_unity_and_teacher(current_unity.id, current_teacher.id).ordered
  end
  helper_method :classrooms

  def knowledge_areas
    @knowledge_areas = KnowledgeArea.by_teacher(current_teacher).ordered
    @knowledge_areas = @knowledge_areas.by_classroom_id(current_user_classroom.id) if current_user_classroom

    @knowledge_areas
  end
  helper_method :knowledge_areas
end

app/views/knowledge_area_content_records/_copy_knowledge_area_content_record_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="copy-knowledge-area-content-record-modal" aria-hidden="true">
  <div class="modal-dialog  modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
        <h4 class="modal-title">Copiar <%= Translator.t('navigation.knowledge_area_content_records').downcase %></h4>
      </div>
      <%= simple_form_for KnowledgeAreaContentRecordClonerForm.new, url: clone_knowledge_area_content_records_path, remote: true, html: { class: 'smart-form' } do |f| %>
      <div class="modal-body">
        <table class="table table-bordered table-striped table-condensed table-hover">
          <thead>
            <tr>
              <th width="30%"><%= ContentRecord.human_attribute_name :classroom %></th>
              <th width="40%"><%= KnowledgeAreaContentRecord.human_attribute_name :knowledge_area_ids %>
              <th width="15%"><%= ContentRecord.human_attribute_name :record_date %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="classroom"></td>
              <td class="knowledge_area"></td>
              <td class="record_date"></td>
            </tr>
          </tbody>
        </table>
        <%= f.input :knowledge_area_content_record_id, as: :hidden %>
        <table class="table table-striped table-bordered table-condensed records">
          <thead>
            <tr>
              <th width="65%"><%= ContentRecord.human_attribute_name :classroom %></th>
              <th width="25%"><%= ContentRecord.human_attribute_name :record_date %></th>
              <th width="10%"></th>
            </tr>
          </thead>
          <tbody id="knowledge-area-content-record-modal-items">
            <%= f.simple_fields_for :knowledge_area_content_record_item_cloner_form do |item| %>
              <%= render 'knowledge_area_content_record_item_cloner_form_fields.html', f: item %>
            <% end %>
          </tbody>
          <tfoot class="links">
            <tr>
              <td colspan="4">
                <%= link_to_add_association t('knowledge_area_content_records.content_fields.add_item'), f, :knowledge_area_content_record_item_cloner_form,
                  class: 'btn btn-success btn-sm', "data-association-insertion-method": "append",
                                                    "data-association-insertion-node": "#knowledge-area-content-record-modal-items" %>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary" >Confirmar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/knowledge_area_content_records/_form.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'list-contents' %>
  <%= javascript_include_tag 'views/knowledge_area_content_records/form' %>
<% end %>

<%= simple_form_for @knowledge_area_content_record, html: { class: 'smart-form' } do |f| %>
  <%= f.error_notification %>

  <%= f.simple_fields_for :content_record, @knowledge_area_content_record.content_record.localized do |content_record| %>
    <%= content_record.hidden_field :id %>

    <fieldset>
      <div class="row">
        <div class="col col-sm-4">
          <%= content_record.input :unity_id, as: :select2, elements: unities, readonly: true %>
        </div>


        <div class="col col-sm-4">
          <%= content_record.association :classroom, as: :select2_classroom, user: current_user,
              record: f.object %>
        </div>

        <div class="col col-sm-4">
          <%= f.input :knowledge_area_ids, as: :select2, elements: knowledge_areas, multiple: true,
                input_html: { data: { without_json_parser: true } }, readonly: f.object.persisted? %>
        </div>
      </div>

      <div class="row">
        <div class="col col-sm-4">
          <%= content_record.input :record_date, as: :date %>
        </div>
      </div>

      <div class="row">
        <div class="col col-sm-12">
          <%= content_record.input :daily_activities_record, as: :text %>
        </div>
      </div>

    </fieldset>
    <fieldset>
      <legend><%= @knowledge_area_content_record.class.human_attribute_name(:contents) %></legend>
      <% if content_record.object.errors[:contents].any? %>
        <div class="alert alert-danger fade in">
          <i class="fa-fw fa fa-times"></i>
          <%= content_record.object.errors[:contents].first %>
        </div>
      <% end %>
        <div class="well" style="max-height: 300px;overflow-y: auto;">
          <ul class="list-group checked-list-box" id="contents-list">

            <% contents.each do |content| %>
              <li class="list-group-item manual" style="display: flex;" id="content_record_<%= content.id %>">
                <%= check_box_tag("knowledge_area_content_record[content_record_attributes][content_ids][]",
                    content.id, content.id.in?(@knowledge_area_content_record.contents.collect(&:id)),
                    hidden: true, 'data-content_description': content.to_s ) %>
                <span style="margin-left: 5px;display: block;width: calc(100% - 85px);"><%= content %></span>
                <% if content.is_editable %>
                  <div style="width: 80px;">
                    <a class="btn btn-success" onclick="editContent('content_record_<%= content.id %>')">
                      <i class="fa fa-pencil"></i>
                    </a>
                    <a class="btn btn-danger" onclick="removeContent('content_record_<%= content.id %>')">
                      <i class="fa fa-trash"></i>
                    </a>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="row textarea contents-select2-container">
          <div class="col col-sm-12">
            <% translation = Translator.t('activerecord.attributes.knowledge_area_content_record.contents') %>
            <%= content_record.input :contents_tags,
                as: :string,
                label: "Adicionar #{translation}",
                input_html: {
                  class: 'select2-content-tags-ajax',
                  value: '',
                  data: {
                    url: contents_path,
                    data: content_record.object.contents_tags,
                    :'filter-by-description' => 1
                  }
                }
            %>
          </div>
        </div>
    </fieldset>

  <% end %>

  <footer>
    <%= link_to t('views.form.back'), knowledge_area_content_records_path, class: 'btn btn-default' %>

    <% if @knowledge_area_content_record.persisted? %>
      <%= link_to t('views.form.history'),
            history_knowledge_area_content_record_path(@knowledge_area_content_record),
            class: 'btn btn-info' %>
    <% end %>

    <%= f.submit t('views.form.save'), class: 'btn btn-primary', data: { disable_with: 'Salvando...'} %>
  </footer>
<% end %>

app/views/knowledge_area_content_records/_knowledge_area_content_record_item_cloner_form_fields.html.erb
<tr class="nested-fields has-no-id">
  <td>
    <%= f.input :classroom_id, as: :select2, label: false %>
  </td>
  <td>
    <%= f.input :record_date, as: :date, label: false %>
  </td>
  <td class="actions">
    <%= f.hidden_field :uuid %>
    <%= link_to_remove_association t('knowledge_area_content_records.content_fields.remove'), f, class: 'btn btn-danger btn-sm' %>
  </td>
</tr>

app/views/knowledge_area_content_records/_resources.html.erb
<tbody id="resources-tbody">
  <% if @knowledge_area_content_records.empty? %>
    <tr>
      <td class="no_record_found" colspan="5"><%= t('views.index.no_record_found')%></td>
    </tr>
  <% else %>
    <% @knowledge_area_content_records.each do |knowledge_area_content_record| %>
      <tr>
        <td class="classroom"><%= knowledge_area_content_record.content_record.classroom %></td>
        <td class="knowledge_area">
          <% knowledge_area_content_record.knowledge_areas.each do |knowledge_area| %>
            <span class="label label-info label-list">
              <%= knowledge_area.description %>
            </span>
          <% end %>
        </td>
        <td class="record_date"><%= l(knowledge_area_content_record.content_record.record_date) %></td>
        <td><%= knowledge_area_content_record.content_record.decorator.author(current_teacher) %></td>
        <td class="actions">
          <%= link_to(
                t('helpers.links.copy_html'),
                '#',
                class: 'btn btn-primary apply_tooltip open_copy_modal',
                data: { original_title: t('views.index.tooltips.copy'),
                        knowledge_area_content_record_id: knowledge_area_content_record.id,
                        classroom_id: knowledge_area_content_record.classroom.id,
                        grade_id: knowledge_area_content_record.classroom.grade_id
                      }) %>
          <%= link_to(
                t('helpers.links.edit_html'),
                edit_knowledge_area_content_record_path(knowledge_area_content_record),
                class: 'btn btn-success apply_tooltip',
                data: { original_title: t('views.index.tooltips.edit') }
              ) %>
          <%= link_to(
                  t('helpers.links.destroy_html'),
                  knowledge_area_content_record_path(knowledge_area_content_record),
                  class: 'btn btn-danger apply_tooltip',
                  disabled: !content_record_destroy?(knowledge_area_content_record.content_record),
                  method: 'delete',
                  data: {
                    confirm: t('views.index.confirm'),
                    original_title: t('views.index.tooltips.delete')
                  }
                ) %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/knowledge_area_content_records/clone.js.erb
<% if @form.errors.any?  %>
    function addErrors(element, text){
      $(element).addClass("error");
      $(element).append('<span class="help-inline error">' + text + '</span>');
    }

    $(".nested-fields div[style*='display']").css("display", "");
    $(".error").removeClass("error");
    $("span.help-inline").remove();

    <% @form.knowledge_area_content_record_item_cloner_form.each do |item| %>
      var uuid = '<%= item.uuid %>';
      <% item.errors.each do |field, message| %>
        var field = '<%= field %>';
        var message = '<%= message %>';
        var element = $('.' + uuid).find("[class*='"+field+"']");
        addErrors(element, message);
      <% end %>
    <% end %>
<% else %>
  location.reload();
<% end %>

app/views/knowledge_area_content_records/edit.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>

app/views/knowledge_area_content_records/history.html.erb
<div class="widget-body">
  <% if resource.all_audits.exists? %>
    <div class="table-responsive">
      <table class="table table-bordered table-only-inner-bordered" id="history">
        <thead>
          <tr>
            <th>Ação</th>
            <th>Alterações</th>
            <th>Autor</th>
            <th>Data</th>
          </tr>
        </thead>
        <tbody>
          <legend> Plano de aula </legend>
          <% resource.content_record.all_audits.each do |audit| %>
            <%= render 'knowledge_area_content_records/history/history', record: AuditDecorator.new(audit) %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="alert alert-warning alert-dismissable">
      Nenhuma alteração realizada.
    </div>
  <% end %>
  </div>

app/views/knowledge_area_content_records/index.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'views/knowledge_area_content_records/index' %>
<% end %>
<div class="widget-body no-padding">
  <%= simple_form_for :filter, { url: knowledge_area_content_records_path, method: :get, html: { class: 'filterable_search_form' } } do |f| %>
    <div class="table-responsive">
      <table id="resources" class="table table-bordered table-only-inner-bordered table-striped table-condensed table-hover">
        <thead>
          <tr>
            <td><%= f.input :by_classroom_description, label: false, placeholder: t('.by_classroom_description') %></td>
            <td><%= f.input :by_knowledge_area_description, label: false, placeholder: t('.by_knowledge_area_description') %></td>
            <td><%= f.input :by_date, as: :date, label: false, placeholder: t('.by_date') %></td>
            <td>
              <%= f.input :by_author, as: :select2_plans, label: false %>
            </td>
            <td>
              <%= link_to t('.new_html'), new_knowledge_area_content_record_path,
                class: 'btn btn-primary pull-right', style: 'width: 120px;' %>
            </td>
          </tr>

          <tr>
            <th><%= ContentRecord.human_attribute_name :classroom %></th>
            <th><%= KnowledgeAreaContentRecord.human_attribute_name :knowledge_areas %>
            <th><%= ContentRecord.human_attribute_name :record_date %></th>
            <th width="10%"><%= KnowledgeAreaContentRecord.human_attribute_name :author %></th>
            <td width="160px"></td>
          </tr>
        </thead>

        <%= render 'resources' %>

        <tfoot id="paginator" class="remote">
          <td id="pagination-tfoot" colspan="5">
            <%= render 'shared/pagination', records: @knowledge_area_content_records %>
          </td>
        </tfoot>
      </table>
    </div>
  <% end %>
</div>
<%= render 'copy_knowledge_area_content_record_modal' %>

app/views/knowledge_area_content_records/index.js.erb
$('#resources-tbody').replaceWith('<%= escape_javascript(render('resources')) %>');
$('#pagination-tfoot').html(
  "<%=
    escape_javascript(render(partial: 'shared/pagination', locals: { records: @knowledge_area_content_records }))
  %>"
);

app/views/knowledge_area_content_records/new.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>