config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get 'worker-processses-status', to: 'sidekiq_monitor#processes_status'

  localized do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }

    namespace :api do
      namespace :v2 do
        resources :exam_rules, only: [:index]
        get 'step_activity', to: 'step_activity#check'
        get 'discipline_activity', to: 'discipline_activity#check'
        get 'student_activity', to: 'student_activity#check'
        resources :teacher_unities, only: [:index]
        resources :teacher_classrooms, only: [:index] do
          collection do
            get :has_activities
          end
        end
        resources :teacher_disciplines, only: [:index]
        resources :school_calendars, only: [:index]
        resources :daily_frequencies, only: [:create, :index]
        resources :daily_frequency_students, only: [:update] do
          collection do
            post :update_or_create
          end
        end
        resources :classroom_students, only: [:index]
        resources :teacher_allocations, only: [:index]
        resources :lesson_plans, only: [:index]
        resources :content_records, only: [:index] do
          collection do
            get :lesson_plans
            post :sync
          end
        end
        resources :teaching_plans, only: [:index]
      end
    end

    concern :history do
      member do
        get :history
      end
    end

    resources :registrations do
      collection do
        get :parents
        get :students
        post :students
        get :employees
        post :employees
      end
    end

    resources :students do
      collection do
        get :search_api
        get :in_recovery
        get :select2_remote
        get :in_final_recovery, path: '/in_final_recovery/classrooms/:classroom_id/disciplines/:discipline_id'
      end
    end

    resources :teachers, only: :index do
      collection do
        get :select2
      end
    end

    resources :teacher_profiles, only: :index

    resources :system_notifications, only: :index

    root 'dashboard#index'

    namespace :dashboard do
      resources :student_partial_scores, only: [:index]
      resources :teacher_next_avaliations, only: [:index]
      resources :teacher_pending_avaliations, only: [:index]
      resources :teacher_work_done_chart, only: [:index]
    end

    post '/current_role', to: 'current_role#set', as: :set_current_role
    get '/current_role/available_classrooms', to: 'current_role#available_classrooms', as: :available_classrooms
    get '/current_role/available_disciplines', to: 'current_role#available_disciplines', as: :available_disciplines
    get '/current_role/available_school_years', to: 'current_role#available_school_years', as: :available_school_years
    get '/current_role/available_teachers', to: 'current_role#available_teachers', as: :available_teachers
    get '/current_role/available_unities', to: 'current_role#available_unities', as: :available_unities
    get '/current_role/available_teacher_profiles', to: 'current_role#available_teacher_profiles', as: :available_teacher_profiles
    get '/steps_by_school_term_type_id', to: 'school_term_type_steps#steps', as: :steps_by_school_term_type_id
    post '/system_notifications/read_all', to: 'system_notifications#read_all', as: :read_all_notifications
    get '/disabled_entity', to: 'pages#disabled_entity'

    resources :users, concerns: :history do
      collection do
        get :export_all
        get :export_selected
        get :select2_remote
        post :profile_picture
      end
    end

    resource :account, only: [:edit, :update]
    resources :roles do
      member do
        get :history
      end
    end
    resources  :user_roles, only: [:show]
    resource :ieducar_api_configurations, only: [:edit, :update], concerns: :history do
      resources :synchronizations, only: [:index, :create] do
        collection do
          get :current_syncronization_data
        end
      end
    end
    resource :general_configurations, only: [:edit, :update], concerns: :history
    resource :entity_configurations, only: [:edit, :update], concerns: :history
    resource :terms_dictionaries, only: [:edit, :update], concerns: :history
    resources :admin_synchronizations, only: [:index]
    resources :backup_files, only: [:index, :create]
    resources :unities, concerns: :history do
      collection do
        delete :destroy_batch
        get :search
        get :all
        get :select2_remote
      end
    end
    resources :courses, only: [:index]
    resources :lectures, only: [:index]
    resources :maintenance_adjustments, concerns: :history, except: :show do
      collection do
        get :any_completed
      end
    end

    resources :grades, only: [:index]

    resources :schools, only: [:index]

    resources :custom_rounding_tables, concerns: :history, except: :show
    resources :custom_rounding_tables, concerns: :history, except: :show

    resources :test_settings, concerns: :history do
      resources :test_setting_tests, only: [:index]
      get :grades_by_unities, on: :collection
    end
    resources :test_setting_tests, only: [:index, :show]

    resources :school_calendar_event_batches
    resources :school_calendars, concerns: :history do
      collection do
        get :step
        get :years_from_unity
      end

      resources :school_calendar_steps, only: [:index]
      resources :school_calendar_events, concerns: :history do
        collection do
          get  :grades
          get  :classrooms
        end
      end
    end
    resources :school_calendar_steps, only: [:show, :index]
    resources :school_calendar_classroom_steps, only: [:show, :index]

    resources :discipline_teaching_plans, concerns: :history
    resources :knowledge_area_teaching_plans, concerns: :history
    resources :learning_objectives_and_skills, concerns: :history do
      collection do
        get :contents
      end
    end

    get '/pedagogical_trackings', as: :pedagogical_trackings, to: 'pedagogical_trackings#index'
    get '/pedagogical_trackings_teachers', as: :pedagogical_trackings_teachers, to: 'pedagogical_trackings#teachers'
    get '/translations', as: :translations, to: 'translations#form'
    post '/translations', as: :save_translations, to: 'translations#save'
    resources :discipline_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
      end
    end
    resources :knowledge_area_lesson_plans, concerns: :history do
      collection do
        post :clone
        get :teaching_plan_contents
        get :teaching_plan_objectives
      end
    end
    resources :discipline_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :knowledge_area_content_records, concerns: :history do
      collection do
        post :clone
      end
    end
    resources :classrooms, only: [:index, :show] do
      resources :students, only: [:index]
    end
    resources :contents, only: :index
    resources :disciplines, only: [:index] do
      collection do
        get :search
        get :search_grouped_by_knowledge_area
      end
    end
    resources :knowledge_areas, only: [:index]
    resources :exam_rules, only: [:index]
    resources :avaliations, concerns: :history do
      collection do
        get :search
        get :multiple_classrooms
        post :create_multiple_classrooms
      end
    end
    resources :complementary_exam_settings, concerns: :history
    resources :complementary_exams, concerns: :history do
      collection do
        get :settings
      end
    end
    resources :teacher_avaliations, only: :index
    resources :daily_notes, only: [:index, :new, :create, :edit, :update, :destroy], concerns: :history do
      collection do
        get :search
      end
    end
    resources :daily_note_students, only: [:index] do
      collection do
        get :old_notes
        get :dependence
      end
    end
    resources :school_term_recovery_diary_records, concerns: :history
    resources :transfer_notes, concerns: :history do
      collection do
        get :current_notes
      end
    end
    resources :final_recovery_diary_records, concerns: :history
    resources :avaliation_recovery_diary_records, concerns: :history
    resources :conceptual_exams, concerns: :history do
      collection do
        get :exempted_disciplines
        get :find_conceptual_exam_by_student
      end
    end
    resources :old_steps_conceptual_values, except: [:only]
    resources :descriptive_exams, only: [:new, :create, :edit, :update], concerns: :history do
      collection do
        get :opinion_types
      end
    end
    resources :daily_frequencies, only: [:new, :create], concerns: :history do
      collection do
        get :edit_multiple
        put :create_or_update_multiple
        delete :destroy_multiple
      end
    end
    get 'daily_frequency/history_multiple', to: 'daily_frequencies#history_multiple', as: 'history_multiple_daily_frequency'

    resources :absence_justifications, concerns: :history
    resources :observation_diary_records, except: :show, concerns: :history
    resources :ieducar_api_exam_postings do
      member do
        get :done_percentage
      end
    end
    resources :avaliation_exemptions, concerns: :history

    resources :daily_frequency_students do
      collection do
        post :create_or_update
      end
    end

    resources :infrequency_trackings, only: :index

    resources :student_enrollments, only: [:index]
    resources :student_enrollments_lists, only: [:index] do
      collection do
        get :by_date
        get :by_date_range
      end
    end

app/views/avaliations/_avaliation_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.input :include, as: :boolean, label: false %>
    <%= f.input :classroom_id, as: :hidden %>
  </td>
  <td>
    <%= f.input :classroom, as: :string, label: false, disabled: true %>
  </td>
  <td>
    <%= f.input :test_date, as: :date, input_html: { value: f.object.localized.test_date }, label: false %>
  </td>

  <td>
    <%= f.input :classes, as: :select2, elements: number_of_classes_elements(@number_of_classes), multiple: true, input_html: { value: f.object.classes.join(','), data: { without_json_parser: true } }, label: false %>
  </td>
</tr>

app/views/avaliations/_form.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'views/avaliations/form' %>
<% end %>
<%= simple_form_for @avaliation, html: { class: "smart-form" } do |f| %>
  <%= f.error_notification %>

  <fieldset>
      <div class="row">
        <div class="col col-sm-4">
          <%= f.association :test_setting, as: :select2, elements: @test_settings, hide_empty_element: true, input_html: { data: { hide_empty_element: true } } %>
        </div>
      </div>

    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :unity, as: :select2_unity, user: current_user %>
      </div>

      <div class="col col-sm-4">
        <%= f.association :classroom, as: :select2_classroom, user: current_user, record: f.object %>
      </div>

      <div class="col col-sm-4">
        <%= f.association :discipline, as: :select2_discipline, user: current_user, record: f.object,
                classroom_id: @avaliation.classroom_id %>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :test_date, as: :date, input_html: { value: f.object.localized.test_date } %>
      </div>

      <div class="col col-sm-4">
        <%= f.input :classes, as: :select2, elements: number_of_classes_elements(@number_of_classes), multiple: true, input_html: { value: f.object.classes.join(','), data: { without_json_parser: true } } %>
      </div>

      <div class="col col-sm-4">
        <%= f.association :test_setting_test, as: :select2, elements: @avaliation.test_setting.tests %>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-4">
        <%= f.input :description, required: true %>
      </div>

      <div class="col col-sm-4">
          <%= f.input :weight, required: true, input_html: { data: { inputmask: "'digits': #{@avaliation.test_setting.number_of_decimal_places}" } } %>
      </div>
    </div>

    <div class="row">
      <div class="col col-sm-12">
        <%= f.input :observations %>
      </div>
    </div>
  </fieldset>

  <footer>
    <%= link_to(t('views.form.back'), avaliations_path, class: 'btn btn-default') %>

    <%= link_to(t('views.form.history'), history_avaliation_path(@avaliation), class: 'btn btn-info') if @avaliation.persisted? %>

    <%= f.submit(t('views.form.save'), class: 'btn btn-primary', data: { disable_with: 'Salvando...'}) %>
    <%= f.submit(t('.save_and_edit_daily_notes'), class: 'btn btn-primary', data: { disable_with: 'Salvando...'}) %>
  </footer>
<% end %>

app/views/avaliations/_resources.html.erb
<tbody id="resources-tbody">
  <% if @avaliations.empty? %>
    <tr>
      <td class="no_record_found" colspan="7"> <%= t('views.index.no_record_found')%></td>
    </tr>
  <% else %>
    <% @avaliations.each do |avaliation| %>
      <tr>
        <td><%= avaliation.unity %></td>
        <td><%= avaliation.classroom %></td>
        <td><%= avaliation.discipline %></td>
        <td><%= l(avaliation.test_date) %></td>
        <td><%= avaliation.current_step %></td>
        <td><%= avaliation %></td>
        <td class="actions">
          <%= link_to t('views.index.edit'), edit_avaliation_path(avaliation), class: 'btn btn-success' %>
          <%= link_to t('views.index.delete'), avaliation_path(avaliation), class: 'btn btn-danger', method: 'delete', data: { confirm: t('views.index.confirm') } %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/avaliations/edit.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>

app/views/avaliations/index.html.erb
<div class="widget-body no-padding">
  <%= simple_form_for :filter, { url: avaliations_path, method: :get, html: { class: 'filterable_search_form' } } do |f| %>
    <div class="table-responsive">
      <table class="table table-bordered table-only-inner-bordered table-striped table-condensed table-hover" id="resources">
        <thead>
          <tr>
            <td></td>
            <td><%= f.input :by_classroom_id, as: :select2, elements: @classrooms, label: false, placeholder: t('.by_classroom_id') %></td>
            <td><%= f.input :by_discipline_id, as: :select2, elements: @disciplines, label: false, placeholder: t('.by_discipline_id') %></td>
            <td>
              <%= f.input :by_test_date, as: :date, label: false,
                    placeholder: t('.by_test_date') %>
            </td>
            <td><%= f.input :by_step_id, as: :select2, elements: @steps, label: false, placeholder: t('.by_step_id') %></td>
            <td><%= f.input :by_description, label: false, placeholder: t('.by_description') %></td>
            <td class="actions" style="width: 160px;">
              <div class="btn-group">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                  <%= t('.new_html') %> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to t('.new_single'), new_avaliation_path %>
                  </li>
                  <li>
                    <%= link_to t('.new_multiple'), multiple_classrooms_avaliations_path %>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
          <tr>
            <th><%= Avaliation.human_attribute_name :unity %></th>
            <th><%= Avaliation.human_attribute_name :classroom %></th>
            <th><%= Avaliation.human_attribute_name :discipline %></th>
            <th><%= Avaliation.human_attribute_name :test_date %></th>
            <th><%= Avaliation.human_attribute_name :step %></th>
            <th><%= Avaliation.human_attribute_name :description %></th>
            <td width="190px"></td>
          </tr>
        </thead>

        <%= render 'resources' %>

        <tfoot id="paginator" class="remote">
          <td colspan="7">
            <div id="page_entries_info" class="pull-left hidden-xs">
              <%= page_entries_info @avaliations %>
            </div>
            <div class="pull-right">
              <%= paginate @avaliations %>
            </div>
          </td>
        </tfoot>
      </table>
    </div>
  <% end %>
</div>

app/views/avaliations/index.js.erb
$('#resources-tbody').replaceWith('<%= escape_javascript(render("resources")) %>');
$('#paginator .pagination').html('<%= escape_javascript(paginate(@avaliations, remote: true).to_s) %>');
$('#page_entries_info').html('<%= escape_javascript(page_entries_info(@avaliations).to_s) %>');

app/views/avaliations/multiple_classrooms.html.erb
<div class="widget-body no-padding">
  <% content_for :js do %>
    <%= javascript_include_tag 'views/avaliations/multiple_classrooms' %>
    <script type="text/javascript">
      window.number_of_classes = <%= @number_of_classes %>;
    </script>
  <% end %>

  <%= simple_form_for @avaliation_multiple_creator_form, url: create_multiple_classrooms_avaliations_path, html: { class: "smart-form" } do |f| %>
    <%= f.error_notification %>
    <%= f.input :school_calendar_id, as: :hidden %>

    <fieldset>
        <div class="row hidden">
          <div class="col col-sm-4">
            <%= f.input :test_setting_id, as: :select2, elements: @test_settings %>
          </div>
        </div>

      <div class="row">
        <div class="col col-sm-4">
          <%= f.input :unity_id, as: :select2_unity, user: current_user %>
        </div>

        <div class="col col-sm-4">
          <%= f.input :discipline_id, as: :select2, elements: disciplines_for_multiple_classrooms %>
        </div>
        <div class="col col-sm-4">
          <%= f.input :test_setting_test_id, as: :select2, elements: @avaliation_multiple_creator_form.test_setting.tests, required: true %>
        </div>
      </div>

      <div class="row">

        <div class="col col-sm-4">
          <%= f.input :description, required: true %>
        </div>

        <div class="col col-sm-4">
            <%= f.input :weight, required: true, input_html: { data: { inputmask: "'digits': #{@avaliation_multiple_creator_form.test_setting.number_of_decimal_places}" } } %>
        </div>
      </div>

      <div class="row">
        <div class="col col-sm-12">
          <%= f.input :observations, as: :text %>
        </div>
      </div>
    </fieldset>
    <fieldset>
      <legend><%= t('.classrooms') %></legend>

      <% if f.object.errors[:avaliations].present? %>
        <div class="alert alert-danger fade in">
          <i class="fa-fw fa fa-times"></i>
          <%= raw f.object.errors[:avaliations].join("<br/>") %>
        </div>
      <% end %>


      <table class="table table-striped table-bordered table-condensed records">
        <thead>
          <tr>
            <th width="5%">
              <div class="control-group boolean optional">
                <div class="controls input">
                  <input value="0" type="hidden" name="select-all">
                  <label class="checkbox">
                    <input class="boolean optional" type="checkbox" value="1" name="select-all" id="select-all">
                    <i></i>
                  </label>
                </div>
              </div>
            </th>
            <th><%= Avaliation.human_attribute_name(:classroom) %></th>
            <th width="25%"><%= Avaliation.human_attribute_name(:test_date) %></th>
            <th width="25%"><%= Avaliation.human_attribute_name(:classes) %></th>
          </tr>
        </thead>

        <tbody id="avaliations">
          <tr>
            <td class="no_item_found" colspan="4" style="<%= @avaliation_multiple_creator_form.avaliations.empty? ? 'display: table-cell;' : 'display: none;' %>" >
              <%= t('.no_classroom_found') %>
            </td>
          </tr>
          <% if f.object.avaliations.present? %>
            <%= f.simple_fields_for :avaliations, f.object.avaliations do |avaliation| %>
              <%= render 'avaliation_fields', f: avaliation %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </fieldset>

    <footer>
      <%= link_to(t('views.form.back'), avaliations_path, class: 'btn btn-default') %>

      <%= link_to(t('views.form.history'), history_avaliation_path(@avaliation), class: 'btn btn-info') if @avaliation_multiple_creator_form.persisted? %>

      <%= f.submit(t('views.form.save'), class: 'btn btn-primary') %>
    </footer>
  <% end %>
</div>

app/views/avaliations/new.html.erb
<div class="widget-body no-padding">
  <%= render 'form' %>
</div>